# Generated by Django 4.0.5 on 2022-06-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_course_options_alter_coursecategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default=True, upload_to='student/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default=True, upload_to='student/'),
        ),
    ]
