# Generated by Django 4.0.5 on 2022-06-10 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_teacher_image_teacher_img_alter_student_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='img',
            new_name='image',
        ),
    ]
