# Generated by Django 4.0.5 on 2022-06-10 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_coursecategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecategory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='image',
        ),
    ]
