# Generated by Django 4.0.5 on 2022-06-10 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_remove_coursecategory_image_remove_teacher_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
